Falkenturm:
#Ob Worldguard Region zum Registrieren und senden von Briefen benutzt werden soll
  verify: true

  Chest:
    #Sollen die Kistendateien von Spielern gelöscht werden Default:false
    Delete: false
    #Wenn ja, nach wie vielen Tagen Inaktivitöt default: 30
    Time: 30

  Letter:
    #Ob Briefe auch an Briefkasten in andere Welten als die derzeitige Spielerwelt gesendet werden können
    to_worlds: true
    #Ob offene Briefe geschlossen werden sollen
    close: true
    #Ob der Author zu ??? geändert werden soll
    change_author: false